### ISSUE TITLE
Strang problem " download .Net "

### ISSUE THREAD

**Issue by KAMELCOLTD** [DineshSolanki/FoliCon#101]
hi
thank you for this tool

i face this problem " to run this app you must install .NET"
even if i clicked Yes download nothing happen 

actually i already installed 5,6,7 dotnet but same problem.

what i did 
i tried leatest version 3.9 same problem
i tried older version 3.9.2 same problem
i tried Self Contained 3.9 nothing happen when i open it ?
i tried older version 3.6.1 x86 it run good but just not working i tested it with many movies but nothing appear ??

i have windows 10 64bit

**Comment by DineshSolanki** [comment]
Can you try installing this https://download.visualstudio.microsoft.com/download/pr/3aa4e942-42cd-4bf5-afe7-fc23bd9c69c5/64da54c8864e473c19a7d3de15790418/windowsdesktop-runtime-5.0.17-win-x64.exe
