### ISSUE TITLE
scaled down icons are too much sharp

### ISSUE THREAD

**Issue by DineshSolanki** [DineshSolanki/FoliCon#107]
Thank You For Your Work i really like the app .. but their is one problem iam facing .. low resolution for icons

_Originally posted by @TheFmC in https://github.com/DineshSolanki/FoliCon/issues/9#issuecomment-1635324548_

**Comment by DineshSolanki** [comment]
@TheFmC

**Comment by TheFmC** [comment]
looks like this 
https://ibb.co/252QXSz

**Comment by DineshSolanki** [comment]
That's not actually low resolution, its happening because the image is high resolution and is scaled down to adjust in size.
you can confirm this by double clicking the image if in professional mode.

but this is something that can be looked into, will keep the issue open.
