### ISSUE TITLE
Rating shows decimal points more than 2, in list and on rating shield

### ISSUE THREAD

**Issue by DineshSolanki** [DineshSolanki/FoliCon#145]
**Describe the bug**
The decimal points of rating should be limited to 2 digits, but its showing more than two

**Screenshots**
![image](https://github.com/DineshSolanki/FoliCon/assets/15937452/da815e05-fb31-4d6d-afd9-e4de5a9df460)

**Additional context**
v3.11.0

**Comment by SSyntax-errorr** [comment]
Hello! I would like to work on this

**Comment by DineshSolanki** [comment]
Sure, create a branch from this issue, once completed, raise a PR

**Comment by DineshSolanki** [comment]
@SSyntax-errorr are you working on this?

**Comment by sarangsmk** [comment]
Hi, @DineshSolanki is progress being made on addressing this matter?

**Comment by DineshSolanki** [comment]
No, would you like to take this up?

**Comment by sarangsmk** [comment]
Yeah I'll take it

**Comment by DineshSolanki** [comment]
> Yeah I'll take it

Sure, please go ahead.
