### ISSUE TITLE
When Faelpessoal poster overlay is selected, and 'use poster overlay is disabled' then the text still shows of the overlay

### ISSUE THREAD

**Issue by DineshSolanki** [DineshSolanki/FoliCon#163]
**Describe the bug**
1. Chose Faelpessoal icon overlay
![image](https://github.com/DineshSolanki/FoliCon/assets/15937452/2e8de3de-3750-4731-8924-a3c1f7e54dac)
2. disable 'use poster overlay' 
3. create an icon, the title text that should only be on overlay, still shows
![image](https://github.com/DineshSolanki/FoliCon/assets/15937452/40ae9501-75f7-4063-a044-2c5d8d3c4223)

**Expected behaviour**
if use poster overlay is disabled, only plain poster should be created.

v3.12.0

**Comment by khanh130202** [comment]
Can you assign me this issue?

**Comment by DineshSolanki** [comment]
> Can you assign me this issue?

Sure,

**Comment by DineshSolanki** [comment]
@khanh130202 are you active on this
