### ISSUE TITLE
Support using folder name metadata

### ISSUE THREAD

**Issue by Soitora** [DineshSolanki/FoliCon#185]
**Is your feature request related to a problem? Please describe.**
Having hundreds of shows, it's quite a lot of manual pressing and checking each windows

**Describe the solution you'd like**
For Plex, I use a [supported standard](https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/#:~:text=If%20you%20are,of%20the%20article.) for folder names.

The series/movie folder structure is `TITLE (YEAR) {tmdb-ID}`
Example: `Chernobyl (2019) {tmdb-87108}`, which would match to: **[Chernobyl](https://www.themoviedb.org/tv/87108-chernobyl)** (from **2019**), with TMDB ID of `87108`.

**Describe alternatives you've considered**
No clear alternative.

**Additional context**
I use Filebot to organize my files, with the size of my media library, this is most optimal for me. Especially as Plex reads them and uses it to know which series to force match.

I suggest, when it finds this in the folder, it forces the entry and doesn't prompt the window for manual confirmation.

**Comment by DineshSolanki** [comment]
Hi, Thanks for reporting this, have you tried using 'Ignore ambiguous title' option (see [docs](https://dineshsolanki.github.io/FoliCon-docs/overview.html).

it will ignore all titles where no exact match is found, so that you will have your exact matches auto created first, this would at least create a poster quickly for all exact matches, 
None the less your suggestion is a better improvement, taking it to development - thanks.

I'm also open to know how would you like the interface for this feature to be, such as should we declare some variables and let you chose where exactly these variable would be in the folder name (something like regex)

**Comment by Soitora** [comment]
Hey, I have not tried ignore ambiguous title yet, I also can't get to have it manually create for folders

Either we run with the format of: Title, anything in (parenthesis) is `year`, and anything in {brackets} is `service-id`, or we let the user define using regex, and specify what regex match is for what field it looks at

**Comment by DineshSolanki** [comment]
@Soitora v3.14-beta released with this change, Feedback are appreciated and will help me get this version release ready,
https://github.com/DineshSolanki/FoliCon/releases/tag/v3.14-beta-1

**Comment by Soitora** [comment]
> @Soitora v3.14-beta released with this change, Feedback are appreciated and will help me get this version release ready, https://github.com/DineshSolanki/FoliCon/releases/tag/v3.14-beta-1

Awesome!
It was almost entirely flawless, it didn't ask me for a single series, it processed all of them, even the ones that are missing here.

Here's the first feedback I can give

## Before running:
| Series (Before) | Movies (Before) |
| --------------- |:---------------:|
| ![Series - before](https://github.com/DineshSolanki/FoliCon/assets/10836780/71deec8c-70c9-4a7c-a706-8dce2e43d0bb) | ![Movies - before](https://github.com/DineshSolanki/FoliCon/assets/10836780/39b0a180-2ace-4bf7-84ed-1b1f7ffb0833) |

## After running:
| Series (After) | Movies (After) |
| --------------- |:---------------:|
| ![Series - after](https://github.com/DineshSolanki/FoliCon/assets/10836780/cf283665-f329-4f03-8a7b-24631c8cf4d0) | ![Movies - after](https://github.com/DineshSolanki/FoliCon/assets/10836780/55829bff-7ba2-45f5-ba41-353e3059df42) |

## Potential issues:

### Not showing for shows with symbols
Maybe use the Title from the show, without any symbols, rather than using the folder name?
![image](https://github.com/DineshSolanki/FoliCon/assets/10836780/47d10076-cc1b-43cd-99e5-49026154fabc)
![image](https://github.com/DineshSolanki/FoliCon/assets/10836780/54de619f-234a-47f2-a8fb-d21cc621ae32)

### Error during Movie run with Collection folders
It errored out from me using the "Collection" folders
![image](https://github.com/DineshSolanki/FoliCon/assets/10836780/269ff740-0ae1-479a-95e1-1d8e190b197e)
