### ISSUE TITLE
Feedback for v3.14-beta-1

### ISSUE THREAD

**Issue by Soitora** [DineshSolanki/FoliCon#190]
The new [v3.14-beta-1](https://github.com/DineshSolanki/FoliCon/releases/tag/v3.14-beta-1) was almost entirely flawless, it didn't ask me for a single series, it processed all of them, even the ones that are missing here.

Here's the first feedback I can give

## Before running:
| Series (Before) | Movies (Before) |
| --------------- |:---------------:|
| ![Series - before](https://github.com/DineshSolanki/FoliCon/assets/10836780/71deec8c-70c9-4a7c-a706-8dce2e43d0bb) | ![Movies - before](https://github.com/DineshSolanki/FoliCon/assets/10836780/39b0a180-2ace-4bf7-84ed-1b1f7ffb0833) |

## After running:
| Series (After) | Movies (After) |
| --------------- |:---------------:|
| ![Series - after](https://github.com/DineshSolanki/FoliCon/assets/10836780/cf283665-f329-4f03-8a7b-24631c8cf4d0) | ![Movies - after](https://github.com/DineshSolanki/FoliCon/assets/10836780/55829bff-7ba2-45f5-ba41-353e3059df42) |

### Not showing for shows with symbols
Maybe use the Title from the show, without any symbols, rather than using the folder name?
![image](https://github.com/DineshSolanki/FoliCon/assets/10836780/47d10076-cc1b-43cd-99e5-49026154fabc)
![image](https://github.com/DineshSolanki/FoliCon/assets/10836780/54de619f-234a-47f2-a8fb-d21cc621ae32)

### Error during Movie run with Collection folders
It errored out from me using the "Collection" folders
![image](https://github.com/DineshSolanki/FoliCon/assets/10836780/269ff740-0ae1-479a-95e1-1d8e190b197e)

**Comment by DineshSolanki** [comment]
Thanks for the feedback, everyone can post here the issues of this version, I'll fix them by the weekend due to some constraint.

**Comment by DineshSolanki** [comment]
@Soitora Please try the beta-2, fixed the mentioned issues

https://github.com/DineshSolanki/FoliCon/releases/tag/v3.14-beta-2


this version changes the icon naming scheme, so you can either use the `delete icon` option from an old folicon version, then use this version to create icons. This is convenient in case you only used poster mode earlier, as this only delete the icons, not the media info associated with it, so FoliCon still knows the exact picked media.

**I have also provided a PowerShell script and steps to use in the release note**

**Comment by Soitora** [comment]
@DineshSolanki after the 2nd beta, it has mostly been flawless, it had no problems doing my 220 folders of anime for example:

![image](https://github.com/DineshSolanki/FoliCon/assets/10836780/81e84de7-73dd-4772-a8f2-03decb75f993)

If I had to request a final touch to the processing, it's to enable sub-folder processing for specifically detected Collection folders (optional?)

**Comment by DineshSolanki** [comment]
@Soitora yeah, makes sense, currently FoliCon only goes deep 1 level, I'll look into it,

**Comment by DineshSolanki** [comment]
I have created a new issue for that and will take it up later on. (maybe v4.1)
I'll keep the beta open for some time before releasing v4.0

**Comment by DineshSolanki** [comment]
Released v4.0 https://github.com/DineshSolanki/FoliCon/releases/
