### ISSUE TITLE
Windows Defender reports 4.0 as Trojan

### ISSUE THREAD

**Issue by Soitora** [DineshSolanki/FoliCon#193]
Simply downloading the files for 4.0 makes Windows Security to remove it

![image](https://github.com/DineshSolanki/FoliCon/assets/10836780/d2603fd0-4a96-4ed3-ae67-73a8c5cb7524)

**Comment by DineshSolanki** [comment]
Is it windows 10, #37

**Comment by Soitora** [comment]
Windows 11 Pro, 24H1

**Comment by DineshSolanki** [comment]
> Windows 11 Pro, 24H1

Okay, I'll try to find the cause, most probably its false positive

**Comment by Soitora** [comment]
Yeah, with the previous versions I've tried it hasn't reported anything as a Virus, only 4.0

**Comment by DineshSolanki** [comment]
The virusTotal report is clean https://www.virustotal.com/gui/url/00220f1464698c66f56725a63bac35f05fca728e25d18828e4fb229116dd4e86/detection

also I'm on win 11 and the defender scan shown clean.

**Comment by DineshSolanki** [comment]
I have sent the files to Microsoft as false positive detection(as their online scan shows a malware also), let's see if I get any reply

![image](https://github.com/DineshSolanki/FoliCon/assets/15937452/faaca76a-53dc-431d-b5ee-7b2cb608c9e4)

**Comment by DineshSolanki** [comment]
internxt.com report
![image](https://github.com/DineshSolanki/FoliCon/assets/15937452/75954907-6d96-4d57-b654-ff207732121e)

**Comment by DineshSolanki** [comment]
Kesarpsky report https://opentip.kaspersky.com/27374550023F1FE0573AB4B6D8FDFA4EA39016BD584C2C2E4104CFEC906C5A48/results?tab=upload

Seems windows defender got some issue.

**Comment by DineshSolanki** [comment]
@Soitora hi can you check with the updated virus definitions, I got a mail from Microsoft saying they fixed this detection
![IMG_20240320_091307.jpg](https://github.com/DineshSolanki/FoliCon/assets/15937452/6a23330c-b629-4ba6-b1e8-553e25d05fb9)

Quoting -
>Hello,

 

Thank you for your recent inquiry about Folicon (submission reference: bf246921-3bf1-4df9-83d1-8244a24c14cc; file reference: folicon v4.0 x64.exe, Sha256: d5b843b366b32db178bb50b6e52dd6cdffacd07ac35c48b85370398a9c84aa7b)  in connection with the operation of Microsoft Defender.

 

The new security intelligence update version [1.407.555.0 & Above] contains changes necessary to resolve your question relating to Folicon. This new security intelligence update is now available for users who subscribe to the automatic security intelligence update mechanism, as well as users who choose to manually update their security intelligence update library.

 

We encourage you to try this new security intelligence update and confirm your inquiry has been resolved.  If your machine has not been updated with this version of security intelligence update you can download and install the update manually following these steps:

Go to https://www.microsoft.com/en-us/wdsi/defenderupdates
Download the corresponding definitions (32 bit or 64 bit based on your operating system)
Run the downloaded file to install the new definitions
 

We apologize for any inconvenience this may have caused.  If you have any additional questions related to this inquiry, please contact us at mpcreply@microsoft.com.  Should you need to contact us in the future regarding a question unrelated to this inquiry, please visit Microsoft Security Intelligence portal  https://www.microsoft.com/en-us/wdsi.

 

 

Sincerely,

Microsoft Defender Response

**Comment by Soitora** [comment]
@DineshSolanki I forgot to respond here, it's now working flawlessly
