### ISSUE TITLE
FoliCon 4.1 tries to match mkv files

### ISSUE THREAD

**Issue by Soitora** [DineshSolanki/FoliCon#196]
**Describe the bug**
FoliCon tries to match my MKV files for whatever reason

**To Reproduce**
Steps to reproduce the behaviour:
1. Icon Mode = Poster
2. Search Mode = TV or Automatic
3. Start

**Expected behaviour**
Posters for series folders to change, not files or folders such as "Season X", "Specials", "Trailers", "Other", etc

**Screenshots**
![image](https://github.com/DineshSolanki/FoliCon/assets/10836780/4abcaf3d-27d7-4a91-85d7-7cde3a80582d)

**Additional context**
None right now.

**Comment by DineshSolanki** [comment]
Hi, it must be the folder name, maybe you extracted the file which created one folder with the same name as the mkv file,
FoliCon really can't detect files when searching so it must be a folder.

on the other hand the issue where it searches for all subfolders come from #190 , to which I'm thinking something such as a customizable regex option, which will have list of pattern which user can customize for search, some common patterns will come bundled with folicon such as 'Season d+'.

**Comment by Soitora** [comment]
> Hi, it must be the folder name, maybe you extracted the file which created one folder with the same name as the mkv file, FoliCon really can't detect files when searching so it must be a folder.

You're right, it was from files that exist in my `.xattr` folders created by Filebot for metadata sakes, could you ignore that and anything inside of it by default? Same goes with `.deletedByTMM` (TinyMediaManager)

> on the other hand the issue where it searches for all subfolders come from https://github.com/DineshSolanki/FoliCon/issues/192 , to which I'm thinking something such as a customizable regex option, which will have list of pattern which user can customize for search, some common patterns will come bundled with folicon such as 'Season d+'.

That could possibly work
