### ISSUE TITLE
I wonder if Folicon also works for Comic Books Collection

### ISSUE THREAD

**Issue by ucapato** [DineshSolanki/FoliCon#199]
**Is your feature request related to a problem? Please describe.**
I felt regret for not finding this tool before. I have a large collection of Comic Books (in .cbz format), and I am working on correctly cataloging them all. As part of this task, I must create folders to sort and classify those Comic books properly. 
Is FoliCon also suitable for this (Search for Comic Book titles, characters, or Publishers for instance)?

**Describe the solution you'd like**
To make FoliCon also suitable for other sources/subjects, such as Comic Books, e-books...
Maybe it could have an additional option during the search as "Comics" for example. Sites like comicvine (https://comicvine.gamespot.com/) has an extend and fast database of Comic content.

If such solution is too much of a troublesome and might bring some limitation (I know ComicVine limits any user by 200 searches/request for each hour), then if FoliCon can be able for user to upload any available image from his PC to make that art as user pleases.

**Describe alternatives you've considered**
I haven't tested the app entirely, but I am assuming there might be a way to properly upload any art or image we want and apply on Folicon to do the job. If that is the case, I believe it could already fit my needs and everyone else interested in such a feature.

**Comment by DineshSolanki** [comment]
Hi @ucapato , your requirement has indeed been requested before https://github.com/DineshSolanki/FoliCon/issues/9#issuecomment-1692815335

And it's in the road map, but for now you should be able to use professional mode to search for comics poster.

And about being able to upload your own image, that is possible in custom icon setter option.

https://dineshsolanki.github.io/FoliCon-docs/custom-icon-setter.html


Currently FoliCon does not support customizing the uploaded icon, but I'm trying to create a plugin system for that.

**Comment by ucapato** [comment]
Wonderful. Thanks a million for that and the quick response.

**Comment by DineshSolanki** [comment]
> Wonderful. Thanks a million for that and thanks for the quick response.

Feel free to play around with FoliCon and don't be hesitant to open an issue, feature request or ask a question should you need to.

**Comment by DineshSolanki** [comment]
@ucapato if FoliCon were to search comicbooks, would it need to search for issue or search for volumes? which one

**Comment by ucapato** [comment]
Hi @DineshSolanki ,

I believe it will be better if search for volumes or series. Like, there Series as Batman, and Volumes like 1940, 2016 (I am guessing the numbers here), so in the end, folders could be like:

Batman v1940
Batman v2016
and so on...

Regards

**Comment by ucapato** [comment]
Hi, 

I am still building up my Comic books folder structure. But I am imaging something like this: 

[Publisher] > [Series] > [Volumes]

e.g.:

DC > Batman > Batman v1940
                       > Batman v2016

and so on.

In terms of arts, this can be very tricky, because every volume in a series might demand a different art. So maybe a better solution could be art only for Publisher and Series. Like the examples below:

For DC Comics:
<img width="423" alt="image" src="https://github.com/user-attachments/assets/e7dd546b-3dc3-4bdf-bb91-e5b041887fcc">

 
For Batman Series:
![image](https://github.com/user-attachments/assets/44e00b46-5ec1-4cbe-b7ab-fe6da6ea2104)
or this:
![image](https://github.com/user-attachments/assets/ed318b5f-6ace-42bc-a60a-0d5d8e965dc9)


Maybe, when reaching the volumes, there could be a more standard art followed by the vXXXX number. But as I said, I think this could lead to a more complexity and maybe uneeded development.
