### ISSUE TITLE
Add feature to chose from zip file when Images are not directly available from DeviantArt as single images

### ISSUE THREAD

**Issue by TheFmC** [DineshSolanki/FoliCon#202]
HI
Is it possible to choose from these 
![folicon](https://github.com/DineshSolanki/FoliCon/assets/95607098/33fd80d3-fca8-488d-abcb-36f320c622de)

**Comment by DineshSolanki** [comment]
Hi, it's currently not possible due to how deviantArt API works, but thanks for bringing my attention to this.
Will try and see what we can do with situation.
