### ISSUE TITLE
can you add a feature to search by id 

### ISSUE THREAD

**Issue by TheFmC** [DineshSolanki/FoliCon#204]
Hello ,
Can u add a feature to search by tmdb id 
![2](https://github.com/user-attachments/assets/54e4f75c-34d1-4f9f-932b-9b483cd8c039)

i couldn't find bgt show 
![1](https://github.com/user-attachments/assets/7ceb12a5-5f6a-4a2a-92b1-dcb663df3321)

**Comment by DineshSolanki** [comment]
The poster mode can search by id
