### ISSUE TITLE
some images don't extract from gallery  .. it stays Empty

### ISSUE THREAD

**Issue by TheFmC** [DineshSolanki/FoliCon#211]
hi again 
sometimes when i try to to extract gallery it doesn't work
![first](https://github.com/user-attachments/assets/7f0d1731-5e3a-4b83-aa41-22a6e7b730cc)
![second](https://github.com/user-attachments/assets/3ac1a031-5ee6-4c81-8ccb-3f85c1b644c2)
great update btw <3

**Comment by DineshSolanki** [comment]
Can you try to download again, delete the existing FoliCon

**Comment by DineshSolanki** [comment]
Okay, I'll look into it.

**Comment by DineshSolanki** [comment]
@TheFmC fixed, please try the latest release.
