### ISSUE TITLE
Not Opening (Windows 10)

### ISSUE THREAD

**Issue by avdichiara** [DineshSolanki/FoliCon#213]
**Describe the bug**
The application (both x64 and x86) fails to launch.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the executable from GitHub
2. Try to run the executable

**Additional context**
FoliCon version: 4.3.1
Windows version: Windows 10 Pro 64-bit (10.0, Build 19045)

I also tried to download the latest versions of .Net and WebView 2. WebView said it was already installed, and I just installed .Net version 8.0.303.

**Comment by DineshSolanki** [comment]
Can you please check the following place -
Search for `Event Viewer` in start menu, then go to `Windows Logs->Application`
and click on folicon entry, there should be something about the crash

![image](https://github.com/user-attachments/assets/3b24908a-9885-4fa5-8153-da06ad6288cd)

**Comment by DineshSolanki** [comment]
Hi, Closing this due to no further response, Please try again with the downloading the fresh release, make sure there's an `NLog.config` file in the same folder as the FoliCon exe.

Feel free to reopen if you still face it.

**Comment by avdichiara** [comment]
Sorry for the slow response. There were several error logs, but the most relevant seems to be:
```
Application: FoliCon.v4.3.1.x64.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at FoliCon.Modules.utils.LogUtils.bKTuyfluxA()
   at FoliCon.Modules.utils.LogUtils.GetNLogConfig()
   at FoliCon.App..ctor()
   at FoliCon.App.Main()
   ```

**Comment by avdichiara** [comment]
I tried creating a new file with the name `NLog.config`, and the error changed to:

```
Application: FoliCon.v4.3.1.x64.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException: The given key 'logDirectory' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NLog.Internal.ThreadSafeDictionary`2.get_Item(TKey key)
   at NLog.Internal.ConfigVariablesDictionary.get_Item(String key)
   at FoliCon.Modules.utils.LogUtils.bKTuyfluxA()
   at FoliCon.Modules.utils.LogUtils.GetNLogConfig()
   at FoliCon.App..ctor()
   at FoliCon.App.Main()
```

I assume this is the root of my issue. Where would I find a proper config file?

**Comment by DineshSolanki** [comment]
@avdichiara Delete the old exe and NLog.config file, and re-download it from here 
https://github.com/DineshSolanki/FoliCon/releases/tag/v4.3.2-beta-1

**Comment by avdichiara** [comment]
I know this is technically a separate issue, but I will include it here. After attempting to use the application, I received an error message `The given key 'p.IconOverlay' was not present in the dictionary.`

**Comment by DineshSolanki** [comment]
@avdichiara no worries, my bad, don't use the beta version, download the latest stable from here https://github.com/DineshSolanki/FoliCon/releases/
