### ISSUE TITLE
Professional mode shows No result Found.

### ISSUE THREAD

**Issue by TheFmC** [DineshSolanki/FoliCon#218]
it was working great .. don't know what happened 
Everytime i try search in Professional Mode.
<img width="646" alt="fix" src="https://github.com/user-attachments/assets/2f0ad2a4-e058-4d80-8104-b0af3bf5ddc3">

**Comment by DineshSolanki** [comment]
> here is my folder 
> ![1](https://github.com/user-attachments/assets/8b5106d3-0387-436b-964f-ba0c970ff133)
> 

The logs are not written... Might be some issue.
I'll look into this soon.

**Comment by DineshSolanki** [comment]
seems like deviantArt removed the endpoint that FoliCon uses https://www.deviantart.com/developers/http/v1/20141204/browse_newest/


I'll look into solution or alternative

**Comment by DineshSolanki** [comment]
@TheFmC im testing a new alternative, might take some more time

**Comment by DineshSolanki** [comment]
@TheFmC It took some time but we have the new version, Please check out https://github.com/DineshSolanki/FoliCon/releases

and close the issue if its fixed.
