### ISSUE TITLE
Different Style Of Icon

### ISSUE THREAD

**Issue by Arrowerse2001** [DineshSolanki/FoliCon#3]
Maybe change the folder icons to something like this https://i.pinimg.com/originals/23/89/74/238974af4662057c1ce9a451f0054bf4.jpg just imo it looks nicer overall it's very good. :)

**Comment by dinesh-solanki** [comment]
The Radio button which says "Professional", does just that. i'm first working on completing one interface so,
Maybe in the next release we would see that

**Comment by DineshSolanki** [comment]
This feature is now available.
62dc8113db78d6c58852870058162097d4f9028a
