### ISSUE TITLE
can't load folders

### ISSUE THREAD

**Issue by MohsenJS** [DineshSolanki/FoliCon#30]
when i click on load and then select my movies folder nothing happen, after load when i click on make icons its say "sorry, internet is not available" but i have internet connection.
![image](https://user-images.githubusercontent.com/17763606/135848129-188a7c3f-001b-488e-99dd-4b798783815d.png)

**Comment by DineshSolanki** [comment]
Load only loads the folder, you can see in the top center, if the path is shown there, it has loaded, so no problem there, as it is shown in screenshot,
About the no internet,
Are you connected to VPN?

**Comment by MohsenJS** [comment]
> Load only loads the folder, you can see in the top center, if the path is shown there, it has loaded, so no problem there, as it is shown in screenshot, About the no internet, Are you connected to VPN?

**Comment by MohsenJS** [comment]
yes, i connected to VPN.
beacuse TMDB is banned in my country

**Comment by DineshSolanki** [comment]
The VPN might be causing this, can you tell me which country vpn you're connected to, so I can test

**Comment by MohsenJS** [comment]
City: Épehy
Region: Hauts-de-France
Country: France

**Comment by MohsenJS** [comment]
i change my vpn and it's work, thanks for amazing app

**Comment by DineshSolanki** [comment]
That's great! ✌️
