### ISSUE TITLE
Windows 10 flags as trojan

### ISSUE THREAD

**Issue by mfb5150** [DineshSolanki/FoliCon#37]
Windows 10 Home
Version: 21H1
OS Build:19043.1348

Trojan: MSIL/RemLoader!MTB

Alert Level: Severe
Status: Active
Date: 11/18/2021 4:40 AM
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

I realize this is most likely a false flag but i thought you should be aware

**Comment by DineshSolanki** [comment]
Interesting, Thanks for informing, Though I checked again from my system also and one other, it is flagged neither by defender nor avast.
can you try downloading a fresh release, and execute directly from zip.

**Comment by DineshSolanki** [comment]
however VirusTotal shows two vendors flagging FoliCon( Rest all says clean), https://www.virustotal.com/gui/file/45930e7f5e8b93a1d1055cf44e847a5c1148ef87d31d52406257761ee88c3c60?nocache=1

as you realize, its a false positive, still I will try to find any code that might be causing false flag.

**Comment by DineshSolanki** [comment]
Closed as false positive.
