### ISSUE TITLE
Clean Poster, Custom Folder Icons and Music folder icons.

### ISSUE THREAD

**Issue by pierx** [DineshSolanki/FoliCon#7]
Hi again,
I would like to suggest you some improvements for your application. Here's some list of it.

- Option to make icons without the rating and the cover template overlay. So it will just look clean movie poster.
- Drag and drop single folder. Once we are done with the batch icons, probably we got a new collection. It would easier to just drag and drop and probably use a custom folder icon that we already have. 
- Music collection folder icon option.

**Comment by DineshSolanki** [comment]
The first option was already in my mind but I didn't thought if that's what many wanted, I'll implement that, and I don't understand the second point about drag and drop single folder

**Comment by pierx** [comment]
Thanks for the response, just scratch that second suggestion, the professional mode already done that.

**Comment by DineshSolanki** [comment]
okay, I'll soon release a version with the suggested features. Thank you so much.

**Comment by pierx** [comment]
Please take your time, the app is already very good. 
Probably you don't realize many hours are saved by using your app, previously I had to do it all manually, browse for the custom folder icon, convert it to .ico if it were png's, browse for the icon, and then set it into a folder one by one.

Now there's no need  to do that anymore, also folicon already put the path .ico inside the folder directly and set the permission automatically, so I don't have to worry of losing the folder icon setup if the folder were copied or moved on external drive or access it from different pc. 
Thanks again for the hard work, keep it up!

**Comment by DineshSolanki** [comment]
These words mean a lot to me because small repos don't get attention and morale to work on them fades over time, I am so happy to know that you found it useful and admire you for taking the time to write how It's useful.

**Comment by DineshSolanki** [comment]
@pierx Hey, I'm a little confused about how the music collection icons should be, do you mean collection by artists or albums? you can also share some names of your music collection folders.

**Comment by DineshSolanki** [comment]
These icons are fetched using the professional mode, where "Reputation" is an album name and "Taylor Swift" an artist name. so I'm searching for more reasons to implement it in poster mode as Rating is not a general part of the music albums.
![image](https://user-images.githubusercontent.com/15937452/84520031-8d3dfd80-acf0-11ea-833f-346dd306efe8.png)

**Comment by pierx** [comment]
Thanks for the update. I think that music album fetched method is good. 
By the way, I have another suggestions;
1. Regarding the professional mode, when searching the image sometimes it took longer than expected, although we already seen the folder icon that we want to use already fetched or showed on the window. So, I think something like a stop searching button would do, or probably send that progress dialog into the background so we can pick the image quickly instead of waiting the search to complete and the go to search the next title directly.
2. An option or checkbox for using google API. I know you already working hard to implement the DeviantArt API, however sometimes for lesser known movie title are not available on deviant art. There's a higher chance it might show up with google API. I think it's fine even with its request per day limit.

**Comment by DineshSolanki** [comment]
The image loading depends on the Network speed, however, I liked the given suggestion about "letting users stop the search in between" I'll open another issue for the same feature.

for the Google API, In fact, chances are very little that you'll find a folder icon on google if it's not on DeviantArt, and the request limit is not feasible as I said before, please see #5 ,

one other thing is if the folder icon in professional mode is like shown below- 
![image](https://user-images.githubusercontent.com/15937452/84563170-36c7d200-ad77-11ea-8ec4-48eb5e3854d4.png)

then an option can be given to the user to manually download it. but then you would have to manually move and change the name of the folder icon file.

**Comment by pierx** [comment]
My connection are good actually, thanks for considering an adding option to stop image loading. 
Sorry I didn't open new issue, just in case you might overwhelmed by these suggestions hehe.
Regarding the google API, i see, thanks for the information.

**Comment by DineshSolanki** [comment]
Yeah your suggestions are good, initially I thought of this but was lazy to do it, 😁.
I'm looking forward for more suggestions and features and feedback, thanks
