### ISSUE TITLE
Error while copying content to a stream

### ISSUE THREAD

**Issue by PoetaGA** [DineshSolanki/FoliCon#91]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. After select all posters
2. And the Folicon try to make the icons
3. apear a box error with that message " Error while copying to a stream"
4. This message appears today, yesterday the app works fine.

**Expected behaviour**
Make the icons

**Screenshots**
![error folicon](https://user-images.githubusercontent.com/28299525/219880348-6c6b1ce3-75ee-4957-aefa-ebfceb9b2bca.jpg)

**Additional context**

**Comment by PoetaGA** [comment]
After some time, working again. Can't explain.

**Comment by DineshSolanki** [comment]
@PoetaGA will still take a look at the error cause, thanks
